"""init

Revision ID: 995270f5d3e8
Revises: 9a60f8b4e524
Create Date: 2025-09-21 03:21:45.517591

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '995270f5d3e8'
down_revision = '9a60f8b4e524'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('assigned_tile', schema=None) as batch_op:
        batch_op.alter_column('scene_id',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=64),
               existing_nullable=False)
        batch_op.alter_column('scene_name',
               existing_type=mysql.VARCHAR(length=255),
               type_=sa.String(length=512),
               nullable=True)
        batch_op.alter_column('label',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_assigned_tile_scene_id'), ['scene_id'], unique=False)
        batch_op.drop_constraint(batch_op.f('assigned_tile_ibfk_1'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'user', ['user_id'], ['id'], ondelete='CASCADE')
        batch_op.drop_column('cols')
        batch_op.drop_column('rows')
        batch_op.drop_column('r')
        batch_op.drop_column('c')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)

    with op.batch_alter_table('assigned_tile', schema=None) as batch_op:
        batch_op.add_column(sa.Column('c', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('r', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('rows', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('cols', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('assigned_tile_ibfk_1'), 'user', ['user_id'], ['id'])
        batch_op.drop_index(batch_op.f('ix_assigned_tile_scene_id'))
        batch_op.alter_column('created_at',
               existing_type=mysql.DATETIME(),
               nullable=False)
        batch_op.alter_column('label',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('scene_name',
               existing_type=sa.String(length=512),
               type_=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('scene_id',
               existing_type=sa.String(length=64),
               type_=mysql.VARCHAR(length=255),
               existing_nullable=False)

    # ### end Alembic commands ###
